### ISSUE TITLE
Nginx MPEGTS testing

### ISSUE THREAD

**Issue by matthiasfostel** [arut/nginx-live-module#3]
I have been testing the Live module for re-transmitting MPEG-TS for a project. I followed your short example and it works but only on the first connection. Each re-connect requires that I restart the Nginx service.
I am wondering if I have something misconfigured or missing a step.
Any pointers on where to start troubleshooting would be helpful.
Thank you in advance!

**Comment by Fisher-mast** [comment]
> I have been testing the Live module for re-transmitting MPEG-TS for a project. I followed your short example and it works but only on the first connection. Each re-connect requires that I restart the Nginx service.
> I am wondering if I have something misconfigured or missing a step.
> Any pointers on where to start troubleshooting would be helpful.
> Thank you in advance!

Same here. Did you solve this problem?

**Comment by matthiasfostel** [comment]
No. I read through the code and could not figure out what was happening so I migrated to a MPEG-Dash solution instead.
